### ISSUE TITLE
Nodemailer support for direct sending

### ISSUE THREAD

**Issue by andris9** [hoodiehq/hoodie-plugins-manager#5]
Hi, just letting you know that Nodemailer (since v0.5.8) is able to send e-mails without any configuration - in this case an outgoing e-mail is delivered directly to the recipients MX server without using a relay service.

This is not the most reliable way for sending e-mails as e-mails sent from a dynamic IP address or from servers without good sending reputation might end up in the Spam folder more easily but it is a really simple way to bootstrap the application.

More information from [Nodemailer docs](https://github.com/andris9/Nodemailer#setting-up-direct-transport)

**Comment by christophwitzko** [comment]
Landed in hoodiehq/hoodie-server@a315a80 :+1:

**Comment by gr2m** [comment]
w00p! Awesome we got this one closed finally :) Thanks again for reporting it @andris9
